baseURL = 'https://huegogh.com/'
languageCode = 'en-us'
title = 'huegogh'
theme = 'hugo-profile'

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]

enableRobotsTXT = true

[pagination]
  pagerSize = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

#[Menus]
  #[[Menus.main]]
    #identifier = "blog"
    #name = "Blog"
    #title = "Blog posts"
    #url = "/blogs"
    #weight = 1
#
  #[[Menus.main]]
    #identifier = "gallery"
    #name = "Gallery"
    #title = "Blog posts"
    #url = "/gallery"
    #weight = 2

[params]
  title = "@huegogh"
  description = "Hugo Mejia, Web Developer"
  favicon = "/fav.png"
  useBootstrapCDN = false
  mathjax = false
  animate = true

  [params.font]
    fontSize = "1rem"
    fontWeight = 400
    lineHeight = 1.5
    textAlign = "left"

  [params.navbar]
    align = "ms-auto"
    brandName = "huegogh"
    disableSearch = true
    enableSeparator = false

    [params.navbar.stickyNavBar]
      enable = true
      showOnScrollUp = true

    [params.navbar.menus]
      disableAbout = false
      disableExperience = false
      disableEducation = false
      disableProjects = true
      disableAchievements = true
      disableContact = false

  [params.hero]
    enable = true
    intro = "Hi, my name is"
    title = "Hugo Mejia."
    subtitle = "I build things for the web"
    content = "A dedicated backend web developer with a strong focus on leveraging modern web technologies to build robust and scalable backend systems for websites."
    image = "/images/hero.jpg"

    [params.hero.bottomImage]
      enable = false

    [params.hero.button]
      enable = false
      name = "Resume"
      url = "#"
      download = true
      newPage = false

    [[params.hero.socialLinks.fontAwesomeIcons]]
      icon = "fab fa-github"
      url = "https://github.com/huegogh"

#    [[params.hero.socialLinks.fontAwesomeIcons]]
#      icon = "fab fa-x-twitter"
#      url = "https://example.com"

#    [[params.hero.socialLinks.customIcons]]
#      icon = "/fav.png"
#      url = "https://example.com"

  [params.about]
    enable = true
    title = "About Me"
    image = "/images/me.png"
    content = """
      I am a web developer with a passion for back-end development.
      """

    [params.about.skills]
      enable = true
      title = "Here are a few technologies I've been working with recently:"
      items = ["Ruby", "Rails", "PostgreSQL", "HTML", "CSS", "JavaScript"]

  [params.experience]
    enable = true

    [[params.experience.items]]
      job = "Software Engineer, Back-End"
      company = "CareRev"
      companyUrl = "https://carerev.com"
      date = "Sept 2021 - Feb 2025"
      content = "I worked as a backend engineer specializing in integrating third-party systems, ensuring seamless communication between external platforms and internal applications."

      [params.experience.items.featuredLink]
        enable = false
        name = "View the project"
        url = "https://example.com"
        content = "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA."

      [params.experience.items.info]
        enable = false
        content = ""

    #[[params.experience.items]]
      #job = "Intern, Software Engineer"
      #company = "Codestack | SJCOE"
      #companyUrl = "https://www.codestack.org/"
      #date = "May 2021 - June 2021"
#
      #[params.experience.items.featuredLink]
        #enable = false
        #url = "https://example.com"
#
      #[params.experience.items.info]
        #enable = false
        #content = ""

  [params.education]
    enable = true
    index = false

    [[params.education.items]]
      title = "Web Development"
      date = "Sept 2020 - Jun 2021"

      [params.education.items.school]
        name = "Codestack Academy | SJCOE"
        url = "https://codestackacademy.org/"

    [[params.education.items]]
      title = "Computer Science"
      date = "Aug 2019 - Jun 2020"

      [params.education.items.school]
        name = "Modesto Junior College"
        url = "https://mjc.edu/"

    [[params.education.items]]
      title = "Computer Science"
      date = "Aug 2012 - Jun 2014"

      [params.education.items.school]
        name = "Los Angeles Valley College"
        url = "https://lavc.edu/"


  [params.achievements]
    enable = false

    [[params.achievements.items]]
      title = "Google kickstart runner"
      content = "I solved all problems with optimal solution."
      url = "https://example.com"
      image = "/images/achievement.jpg"

    [[params.achievements.items]]
      title = "Facebook Hackathon Winner"
      content = "Developed a product using Artificial Intelligence."
      image = "/images/achievement.jpg"

  [params.projects]
    enable = false

    [[params.projects.items]]
      title = "Hugo Profile"
      content = "A highly customizable and mobile first Hugo template for personal portfolio and blog."
      image = "/images/projects/profile.png"

      [params.projects.items.featured]
        name = "Demo"
        link = "https://hugo-profile.netlify.app"

      badges = ["Hugo", "Bootstrap", "Javascript"]

      [[params.projects.items.links]]
        icon = "fab fa-github"
        url = "https://github.com/gurusabarish/hugo-profile"

  [params.contact]
    enable = true
    content = "Looking to hire? Please contact me for a resume. Otherwise, feel free to reach out and say hi! 👋"
    btnName = "hugo@huegogh.com"
    btnLink = "mailto:hugo@huegogh.com"

  [params.footer]
    [params.footer.recentPosts]
      path = "blogs"
      count = 3
      title = "Recent Posts"
      enable = true
      disableFeaturedImage = false

    [params.footer.socialNetworks]
      github = "https://github.com/huegogh"
      linkedin = "https://www.linkedin.com/in/hugo-mejia-49122b351/"
      #twitter = "https://twitter.com"
      instagram = "https://instagram.com/huegogh.makes"
      #facebook = "https://facebook.com"

  [params.listPages]
    disableFeaturedImage = false

  [params.singlePages]
    socialShare = true

    [params.singlePages.readTime]
      enable = true
      content = "min read"

    [params.singlePages.scrollprogress]
      enable = true

    [params.singlePages.tags]
      openInNewTab = true

  [params.terms]
    read = "Read"
    toc = "Table Of Contents"
    copyright = "All rights reserved"
    pageNotFound = "Page not found"
    emailText = "<greeting>Hello!</greeting>"

  [params.datesFormat]
    article = "Jan 2, 2006"
    articleList = "Jan 2, 2006"
    articleRecent = "Jan 2, 2006"
